name: Add File to Bucket
on:
  push:
    branches:
      - main
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: deploy-upyun
        uses: bwcxyk/upyun-upx-action@1.3
        env:
          UPX_SERVICENAME: ${{ secrets.UPX_SERVICENAME }}
          UPX_OPERATOR: ${{ secrets.UPX_OPERATOR }}
          UPX_PASSWORD: ${{ secrets.UPX_PASSWORD }}
          LOCAL_DIR: ./docs/
          REMOTE_DIR: /
