name: Add File to Bucket
on:
  workflow_run:
    workflows: [build Gmeek]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@v3
      - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: Wait for 3 minutes
        run: sleep 180 # 等待 30s，单位为秒    
      - name: deploy-upyun
        uses: bwcxyk/upyun-upx-action@1.3
        env:
          UPX_SERVICENAME: ${{ secrets.UPX_SERVICENAME }}
          UPX_OPERATOR: ${{ secrets.UPX_OPERATOR }}
          UPX_PASSWORD: ${{ secrets.UPX_PASSWORD }}
          LOCAL_DIR: ./docs/
          REMOTE_DIR: /
      - name: Wait for 3 minutes
        run: sleep 30 # 等待 30s，单位为秒
        
      - name: 又拍云刷新
        uses: yiyungent/upyun-action@main
        with:
            upyun_username: ${{ secrets.UPYUN_USERNAME }}
            upyun_password: ${{ secrets.UPYUN_PASSWORD }}
            refresh_cache_urls: "https://blog.freeblock.cn/*"   
     
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Wait for 3 minutes
        run: sleep 60 # 等待 90s，单位为秒
      - name: 多吉云刷新
        env:
            ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pip install requests
          python .github/refresh-dogecloud.py
            
