- name: 部署到云服务器
  uses: cross-the-world/scp-pipeline@master
  with:
    host: ${{ secrets.USER_HOST }}
    user: ${{ secrets.USER_NAME }}
    pass: ${{ secrets.USER_PASS }}
    connect_timeout: 10s
    local: './public/*'
    remote: /www/wwwroot/hexo
