name: 部署到云服务器
on:
  push:
    branches:
      - main
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
  uses: cross-the-world/scp-pipeline@master
  with:
    host: ${{ secrets.USER_HOST }}
    user: ${{ secrets.USER_NAME }}
    pass: ${{ secrets.USER_PASS }}
    connect_timeout: 10s
    local: './public/*'
    remote: /www/wwwroot/hexo
