# 案例配置
# 工作流名称
name: 'deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  issues:
    types: [opened, edited]

# 作业
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: docs/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          # 指定排除上传的文件
          EXCLUDE: "/node_modules/"
